version: 2
jobs:
  build:
    docker:
      # new standalone docker container
      - image: fr3akyphantom/droid-builder:latest
    environment:
      MANIFEST_BRANCH: 'twrp-6.0'
      # PBRP_BRANCH: optional, if not default 'android-9.0', define other bootable_recovery branch
      VERSION: '2.9.0' # as of now, the current PBRP version
      VENDOR: 'samsung'
      CODENAME: 'gtaxllte'
      BUILD_LUNCH: 'omni_gtaxllte-userdebug'
      TEST_BUILD: 'true'
      # PB_OFFICIAL: 'true'
      # EXTRA_CMD: # some required commands like `ls` after `repo sync`, write in single line
    working_directory: /home/builder/pitchblack
    steps:
      - checkout
      - run:
          name: AIO Build
          command: |
            echo "Set GitAuth Infos"
            git config --global user.email $GitHubMail
            git config --global user.name $GitHubName
            git config --global color.ui true
            wget -q https://raw.githubusercontent.com/PitchBlackRecoveryProject/vendor_pb/pb/build.sh
            source build.sh
workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only: 'android-6.0'
          context: org-global
